include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"      # archivos generados por build_runner / isar_generator
    - "**/*.freezed.dart"
  errors:
    experimental_member_use: ignore

linter:
  rules:
    avoid_print: false   # usamos logging, pero print es aceptable en main/cli
