; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PrismHub"
; Tiene que coincidir con Compartir.esquema (lib/utils/compartir.dart)
; y con el intent-filter de AndroidManifest.xml.
#define MyAppScheme "prismhub"
#define MyAppPublisher "PrismHub"
#define MyAppURL "https://github.com/Litdemonick/Prism_Hub"
#define MyAppExeName "PrismHub.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3C6BC9E1-F61D-4FD6-BDA6-3BC203E88418}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; En una ACTUALIZACION no se pregunta por la carpeta.
;
; "auto" salta esa pagina cuando el instalador encuentra una instalacion previa
; —la reconoce por AppId— y usa la carpeta que ya tenia. Sin esto la mostraba
; siempre, y como la carpeta obviamente existe, salia encima un "La carpeta ya
; existe, ¿instalar ahi de todas formas?": dos preguntas seguidas que suenan a
; problema cuando lo unico que se esta haciendo es actualizar.
;
; En una instalacion NUEVA se sigue mostrando, que ahi si hace falta poder
; elegir donde va.
DisableDirPage=auto
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PrismHub-setup-{#MyAppVersion}
SetupIconFile=.\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Sin esto, ni instalar (sobre una versión ya corriendo) ni desinstalar
; cierran el proceso — Windows no mata un .exe corriendo solo porque se
; borró el archivo del disco, así que quedaba corriendo "fantasma" después
; de desinstalar. CloseApplications usa Restart Manager para detectarlo y
; cerrarlo (force = sin preguntar); RestartApplications=no porque no tiene
; sentido reabrir el reproductor solo.
CloseApplications=force
RestartApplications=no
; Idioma automático según Windows, sin preguntar. Inno 6 detecta solo por el
; idioma de la interfaz del sistema (la directiva LanguageDetection de Inno 5
; ya no existe: usarla aborta la compilación). Ver [Languages].
;
; Y se PREGUNTA, con el idioma detectado ya elegido por defecto.
;
; Antes estaba en "no" para no agregar una pregunta más, pero eso dejaba al
; usuario sin forma de cambiarlo: si la detección erraba —o simplemente quería
; el instalador en el otro idioma— no había manera. Ahora se muestra la lista
; con el detectado ya seleccionado, así que a quien le sirve ese le alcanza con
; Aceptar, y el resto puede cambiarlo.
;
; Lo elegido acá vale para TODO el instalador: bienvenida, botones y avisos.
ShowLanguageDialog=yes
; Y NO reutilizar el idioma de la instalacion anterior, que es lo que hace Inno
; por defecto (UsePreviousLanguage=yes). Al actualizar, Setup lee el valor
; "Inno Setup: Language" que dejo la instalacion previa y lo usa tal cual, sin
; llegar a detectar nada. Como las versiones hasta la 1.0.13 se publicaron con
; el instalador solo en ingles, ese valor quedo grabado como "english" en todas
; las maquinas: por mas que ahora se declare el espanol, la deteccion no
; alcanzaba a correr y el instalador seguia saliendo en ingles. Confirmado
; leyendo esa clave en una instalacion real.
UsePreviousLanguage=no
; La pantalla de bienvenida viene DESACTIVADA por defecto en Inno 6, y es
; justamente donde se avisa si esto es una actualización y entre qué versiones
; (ver InitializeWizard). Sin ella, el instalador arrancaba directo en "elegí
; carpeta" y nunca decía qué se estaba instalando ni sobre qué.
DisableWelcomePage=no
; Muestra "PrismHub <versión>" en el título del asistente.
AppVerName={#MyAppName} {#MyAppVersion}

[Languages]
; El instalador salía siempre en inglés, aunque Windows estuviera en español.
; Inno elige solo según el idioma de Windows y no pregunta nada
; (ShowLanguageDialog=no); si el sistema está en cualquier otro idioma cae en el
; primero de la lista, que es inglés.
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[CustomMessages]
; %1 = versión instalada, %2 = versión que se va a instalar.
; ── Actualizar: hay una version ANTERIOR instalada ──────────────────────────
english.PrismUpdateTitle=⬆️ Updating PrismHub
spanish.PrismUpdateTitle=⬆️ Actualizando PrismHub
english.PrismUpdateBody=You already have PrismHub %1. It will be updated to %2.%n%n✅ Your history, favourites, settings and installed extensions are KEPT — they live outside the program folder.%n🧹 The program folder is emptied before copying, so no leftovers from the old version remain.%n🔄 Extensions update on their own, no need to reinstall them.
spanish.PrismUpdateBody=Ya tenés PrismHub %1. Se va a actualizar a la %2.%n%n✅ Tu historial, favoritos, ajustes y extensiones instaladas se CONSERVAN — viven fuera de la carpeta del programa.%n🧹 La carpeta del programa se vacía antes de copiar, así no quedan restos de la versión vieja.%n🔄 Las extensiones se actualizan solas, no hace falta reinstalarlas.
; ── Reinstalar: la MISMA version que ya esta instalada ──────────────────────
english.PrismRepairTitle=🔄 Reinstalling PrismHub
spanish.PrismRepairTitle=🔄 Reinstalando PrismHub
english.PrismRepairBody=You already have PrismHub %1 — the same version this installer carries.%n%n♻️ The program files will be replaced with the original ones. Useful if something got corrupted, was deleted, or the app stopped opening.%n✅ Your history, favourites, settings and installed extensions are KEPT.
spanish.PrismRepairBody=Ya tenés PrismHub %1 — la misma versión que trae este instalador.%n%n♻️ Se van a reemplazar los archivos del programa por los originales. Sirve si algo se corrompió, se borró, o la app dejó de abrir.%n✅ Tu historial, favoritos, ajustes y extensiones instaladas se CONSERVAN.
; ── Volver atras: el instalador trae una version ANTERIOR a la instalada ────
english.PrismDowngradeTitle=⬇️ Going back to an earlier version
spanish.PrismDowngradeTitle=⬇️ Volviendo a una versión anterior
english.PrismDowngradeBody=You have PrismHub %1, and this installer carries %2 — which is older.%n%n⚠️ You will lose the fixes and features added after %2.%n✅ Your history, favourites, settings and extensions are KEPT, so you can go forward again whenever you want.
spanish.PrismDowngradeBody=Tenés PrismHub %1 y este instalador trae la %2, que es anterior.%n%n⚠️ Vas a perder los arreglos y las novedades agregadas después de la %2.%n✅ Tu historial, favoritos, ajustes y extensiones se CONSERVAN, así que podés volver a adelantar cuando quieras.
; ── Instalacion nueva: nunca se instalo en este equipo ──────────────────────
english.PrismFreshTitle=🎉 Installing PrismHub
spanish.PrismFreshTitle=🎉 Instalando PrismHub
english.PrismFreshBody=PrismHub %1 will be installed on this computer.%n%n📺 Anime, manga and series through extensions that install and update on their own.%n📡 Cast to your TV, Chromecast or Roku from the same screen.%n💾 Your history, favourites and settings are saved outside the program folder, so uninstalling never takes them by surprise.%n🔒 Nothing is uploaded anywhere: everything stays on this computer.
spanish.PrismFreshBody=Se va a instalar PrismHub %1 en este equipo.%n%n📺 Anime, manga y series mediante extensiones que se instalan y actualizan solas.%n📡 Transmití a tu televisor, Chromecast o Roku desde la misma pantalla.%n💾 Tu historial, favoritos y ajustes se guardan fuera de la carpeta del programa, así desinstalar nunca se los lleva de sorpresa.%n🔒 No se sube nada a ningún lado: todo queda en este equipo.
; Al desinstalar. Se PREGUNTA en vez de borrar directo: mucha gente desinstala
; para reinstalar, y llevarse el historial sin avisar no se puede deshacer.
english.PrismWipeTitle=Remove your data as well?
spanish.PrismWipeTitle=¿Borrar también tus datos?
english.PrismWipeBody=Do you also want to delete your history, favourites, settings and installed extensions?%n%nThey live outside the program folder, so by default they are KEPT — that way reinstalling picks up where you left off.%n%nChoose Yes only if you want to leave nothing behind. This cannot be undone.
spanish.PrismWipeBody=¿Querés borrar también tu historial, favoritos, ajustes y extensiones instaladas?%n%nEstán fuera de la carpeta del programa, así que por defecto se CONSERVAN — así, si reinstalás, seguís donde estabas.%n%nElegí Sí solo si no querés que quede ningún rastro. Esto no se puede deshacer.
english.PrismWipeDone=Your data was deleted.
spanish.PrismWipeDone=Se borraron tus datos.
english.PrismFirewall=Allowing PrismHub through the firewall (needed to cast to a TV)...
spanish.PrismFirewall=Permitiendo PrismHub en el firewall (hace falta para transmitir a un televisor)...
english.PrismWipeKept=Your data was kept at:%n%1
spanish.PrismWipeKept=Tus datos se conservaron en:%n%1
; Nota que se agrega SIEMPRE a la pantalla de bienvenida.
; Texto del boton de la pagina "Listo para instalar", segun el caso.
english.PrismBtnFresh=&Install
spanish.PrismBtnFresh=&Instalar
english.PrismBtnUpdate=&Update
spanish.PrismBtnUpdate=&Actualizar
english.PrismBtnRepair=&Reinstall
spanish.PrismBtnRepair=&Reinstalar
english.PrismBtnDowngrade=&Go back
spanish.PrismBtnDowngrade=&Volver atrás
english.PrismUnsignedNote=%n%n⚠️ Note: PrismHub is not digitally signed, so Windows SmartScreen or your antivirus may warn about it or block it. If that happens, choose "More info" and then "Run anyway", or allow it in your antivirus.
spanish.PrismUnsignedNote=%n%n⚠️ Nota: PrismHub no está firmado digitalmente, así que Windows SmartScreen o tu antivirus pueden avisarte o bloquearlo. Si pasa, elegí "Más información" y después "Ejecutar de todas formas", o permitilo en tu antivirus.
; Aviso fuerte, SOLO si se detecta Smart App Control encendido.
english.PrismSacTitle=Windows may block this installation
spanish.PrismSacTitle=Windows puede bloquear esta instalación
english.PrismSacBody=This computer has Smart App Control turned on.%n%nThat Windows 11 feature blocks programs that are not digitally signed, and PrismHub is not. The install may fail, or the program may refuse to open with a "Bad Image" error naming a .dll file.%n%nIf that happens, turn it off in:%nWindows Security > App & browser control > Smart App Control.%n%nIMPORTANT: Windows does NOT let you turn it back on afterwards without reinstalling the system. Think it over before you do it.%n%nYou can continue anyway — if the program opens fine, there is nothing to change.
spanish.PrismSacBody=Este equipo tiene Smart App Control activado.%n%nEsa función de Windows 11 bloquea los programas que no están firmados digitalmente, y PrismHub no lo está. La instalación puede fallar, o el programa puede negarse a abrir con un error de "Imagen incorrecta" que nombra un archivo .dll.%n%nSi pasa, desactivalo en:%nSeguridad de Windows > Control de aplicaciones y explorador > Smart App Control.%n%nIMPORTANTE: Windows NO deja volver a activarlo después sin reinstalar el sistema. Pensalo antes de hacerlo.%n%nPodés continuar igual — si el programa abre bien, no hay nada que tocar.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Enlaces compartidos: prismhub://detail?package=...&url=...
;
; Windows resuelve un esquema propio mirando HKCR\<esquema>. Sin estas claves,
; el enlace que alguien recibe por chat es texto muerto: no hay nada que le
; diga al sistema que PrismHub lo entiende.
;
; Van bajo Software\Classes del usuario y no en HKEY_CLASSES_ROOT a secas: el
; instalador puede correr sin permisos de administrador, y ahi HKCR no se puede
; escribir. Registrado por usuario funciona igual para quien instalo.
;
; "URL Protocol" tiene que existir aunque este vacio — es la marca por la que
; Windows reconoce la clave como un esquema y no como un tipo de archivo.
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}"; ValueType: string; ValueName: ""; ValueData: "URL:{#MyAppName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
; El "%1" es la direccion completa que se abrio, y va entre comillas porque
; puede traer espacios y ampersands: sin ellas el enlace llega cortado en el
; primer simbolo raro.
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Permiso de FIREWALL para transmitir a un televisor.
;
; Al castear, el video no lo baja el televisor de internet: lo sirve ESTE
; equipo, que abre un servidor en la red local y le pasa la direccion. Windows
; bloquea por defecto las conexiones entrantes de un programa sin regla, asi
; que el televisor pedia el video y no le contestaba nadie — se quedaba en
; negro con la barra en 00:00 y desde afuera parecia que el televisor no
; soportaba el formato. Comprobado en un equipo real: cero reglas para el app y
; politica de entrada en bloquear.
;
; Solo en redes privadas (domesticas): en una red publica no hay nada que
; transmitir y no corresponde abrir nada.
;
; skipifdoesntexist: si el instalador corre sin permisos de administrador la
; regla no se va a poder crear, y eso no es motivo para que falle la
; instalacion — el casteo es una funcion mas, no el app entero.
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"""; Flags: runhidden waituntilterminated skipifdoesntexist; StatusMsg: "{cm:PrismFirewall}"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes profile=private"; Flags: runhidden waituntilterminated skipifdoesntexist; StatusMsg: "{cm:PrismFirewall}"
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Se quita al desinstalar: una regla apuntando a un programa que ya no existe
; no hace daño, pero tampoco tiene por que quedar.
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"""; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "QuitarReglaFirewall"

[Code]
// Los cuatro casos posibles, decididos una sola vez en InitializeWizard y
// reusados para el texto de bienvenida y para el botón de "Listo para
// instalar" (ver QueSeEstaHaciendo).
const
  casoInstalar = 0;
  casoActualizar = 1;
  casoReinstalar = 2;
  casoVolverAtras = 3;

var
  // Ya se avisó de Smart App Control en esta corrida (ver CurPageChanged).
  AvisoSacMostrado: Boolean;
  CasoDeEstaCorrida: Integer;

// La versión llega desde el workflow como nombre del tag ("v1.0.13"), y lo
// mismo quedó guardado en el registro. Mostrarla tal cual daba "versión
// v1.0.13"; se le saca la v para que el texto se lea normal.
function SinV(const S: String): String;
begin
  Result := S;
  if (Length(Result) > 1) and ((Result[1] = 'v') or (Result[1] = 'V')) then
    Result := Copy(Result, 2, Length(Result) - 1);
end;

// Versión que ya está instalada, leída de la clave de desinstalación que crea
// el propio Inno. Cadena vacía si es una instalación nueva.
//
// OJO: el GUID va literal y tiene que coincidir con AppId de [Setup]. No se usa
// SetupSetting("AppId") porque ahí el valor viene con la llave doble de escape
// ({{...}) y quedaría una llave de más en la ruta del registro.
//
// Se miran las dos vistas del registro y las dos raíces: el instalador corre en
// 32 bits, así que HKLM le resuelve a Wow6432Node, pero una instalación hecha
// por otro medio pudo dejar la clave en la vista de 64 bits o por usuario.
function VersionInstalada(): String;
var
  Clave: String;
  Valor: String;
begin
  Result := '';
  Clave := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{3C6BC9E1-F61D-4FD6-BDA6-3BC203E88418}_is1';
  if RegQueryStringValue(HKLM, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKCU, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKLM64, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKCU64, Clave, 'DisplayVersion', Valor) then
    Result := Valor;
end;

// Al ACTUALIZAR, se vacía la carpeta del programa antes de copiar lo nuevo.
//
// Inno por defecto solo SOBRESCRIBE: lo que la versión nueva ya no trae —una
// dll de un plugin que se sacó, un archivo que cambió de nombre, restos de una
// versión de hace meses— se queda ahí para siempre. Y no es basura inofensiva:
// Windows busca las dll al lado del .exe, así que el programa nuevo termina
// cargando una dll vieja que ya no le corresponde. De ahí salen los "Imagen
// incorrecta" señalando una dll suelta que en realidad no está rota, es de
// otra versión.
//
// Tus datos NO están acá y por eso vaciar esto no toca nada tuyo: el
// historial, los favoritos, los ajustes y las extensiones instaladas viven en
// {userdocs}\PrismHub, {userappdata}\com.prismhub y la caché — las tres fuera
// de la carpeta del programa (ver CarpetaDatos, CarpetaCache y
// CarpetaSoporte). Es lo mismo que ya dice la pantalla de bienvenida al
// actualizar.
//
// Se saltan los "unins*": son el desinstalador de la instalación en curso.
procedure VaciarCarpetaDelPrograma(const Carpeta: String);
var
  Busqueda: TFindRec;
  Nombre: String;
begin
  if not DirExists(Carpeta) then
    exit;
  if not FindFirst(AddBackslash(Carpeta) + '*', Busqueda) then
    exit;
  try
    repeat
      Nombre := Busqueda.Name;
      if (Nombre = '.') or (Nombre = '..') then
        continue;
      if Pos('unins', Lowercase(Nombre)) = 1 then
        continue;
      if (Busqueda.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
        DelTree(AddBackslash(Carpeta) + Nombre, True, True, True)
      else
        DeleteFile(AddBackslash(Carpeta) + Nombre);
    until not FindNext(Busqueda);
  finally
    FindClose(Busqueda);
  end;
end;

// ssInstall es justo antes de copiar los archivos, y después de que
// CloseApplications haya cerrado el programa si estaba corriendo. Vaciar antes
// de eso dejaría las dll tomadas por el proceso vivo y no se borrarían.
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    VaciarCarpetaDelPrograma(ExpandConstant('{app}'));
end;

// Dónde deja el app sus cosas, fuera de la carpeta del programa.
//
// {userdocs} y NO una ruta armada a mano: la carpeta Documentos puede estar
// redirigida a OneDrive y además traducida —comprobado en un equipo real, ahí
// vive en OneDrive\Documentos\PrismHub—. Esa constante la resuelve Windows, así
// que sigue la redirección; una ruta fija habría borrado la carpeta equivocada,
// o peor, ninguna, dejando creer que se limpió.
function CarpetaDatos(): String;
begin
  Result := ExpandConstant('{userdocs}\PrismHub');
end;

function CarpetaCache(): String;
begin
  Result := ExpandConstant('{localappdata}\Temp\PrismHub');
end;

function CarpetaSoporte(): String;
begin
  Result := ExpandConstant('{userappdata}\com.prismhub');
end;

// Al desinstalar: se pregunta y, si el usuario quiere, se borra todo.
//
// usPostUninstall y no usUninstall: recién ahí ya se quitaron los archivos del
// programa, así que si algo falla al borrar los datos el desinstalado igual
// quedó hecho.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Datos: String;
  Borrados: Boolean;
begin
  if CurUninstallStep <> usPostUninstall then
    exit;

  Datos := CarpetaDatos();
  // Sin datos guardados no se pregunta nada: sería una ventana de más para
  // decidir sobre algo que no existe.
  if not DirExists(Datos) and not DirExists(CarpetaCache())
     and not DirExists(CarpetaSoporte()) then
    exit;

  if MsgBox(CustomMessage('PrismWipeBody'), mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
  begin
    Borrados := True;
    if DirExists(Datos) then
      if not DelTree(Datos, True, True, True) then Borrados := False;
    if DirExists(CarpetaCache()) then
      if not DelTree(CarpetaCache(), True, True, True) then Borrados := False;
    if DirExists(CarpetaSoporte()) then
      if not DelTree(CarpetaSoporte(), True, True, True) then Borrados := False;
    // Se avisa igual aunque algo no se haya podido borrar: quedarse callado
    // dejaría creer que no quedó nada cuando sí quedó.
    if Borrados then
      MsgBox(CustomMessage('PrismWipeDone'), mbInformation, MB_OK)
    else
      MsgBox(FmtMessage(CustomMessage('PrismWipeKept'), [Datos]), mbInformation, MB_OK);
  end
  else
    // Se dice DÓNDE quedaron: si no, el usuario no tiene forma de encontrarlos
    // para borrarlos a mano más adelante.
    MsgBox(FmtMessage(CustomMessage('PrismWipeKept'), [Datos]), mbInformation, MB_OK);
end;

// Smart App Control encendido.
//
// Es la funcion de Windows 11 que bloquea binarios sin firma ni reputacion.
// PrismHub no esta firmado, asi que con esto activo la instalacion puede
// fallar o el .exe negarse a abrir con "Imagen incorrecta" (0xc0e90002)
// senalando una dll cualquiera — el error no dice ni una palabra de Smart App
// Control, asi que desde afuera parece un archivo roto. Comprobado en un
// equipo real: el mismo instalador anda en una maquina y en la otra no, y lo
// unico distinto era este valor.
//
// 0 = apagado, 1 = bloqueando, 2 = en evaluacion. Solo el 1 molesta.
//
// Vive bajo HKLM\SYSTEM, que NO tiene redireccion de 32/64 bits (solo la tiene
// SOFTWARE), asi que se lee igual aunque el instalador corra en 32 bits. En
// Windows 10 la clave no existe y esto devuelve False, que es lo correcto:
// ahi la funcion no existe.
function SmartAppControlBloqueando(): Boolean;
var
  Estado: Cardinal;
begin
  Result := False;
  if RegQueryDWordValue(HKLM, 'SYSTEM\CurrentControlSet\Control\CI\Policy',
                        'VerifiedAndReputablePolicyState', Estado) then
    Result := (Estado = 1);
end;

// Qué está pasando realmente en esta corrida. No alcanza con "¿hay algo
// instalado?": reemplazar la MISMA versión, subir de versión y volver a una
// anterior son tres cosas distintas, y decirle "actualizando" a alguien que
// está reinstalando por tercera vez porque la app no le abre es mentirle.
function QueSeEstaHaciendo(const Anterior: String): Integer;
var
  Vieja, Nueva: Int64;
begin
  if Anterior = '' then
  begin
    Result := casoInstalar;
    exit;
  end;
  // Comparación por texto primero: si son idénticas no hace falta más, y cubre
  // el caso de una versión con un formato que StrToVersion no sepa leer.
  if CompareText(SinV(Anterior), SinV('{#MyAppVersion}')) = 0 then
  begin
    Result := casoReinstalar;
    exit;
  end;
  // Si alguna no se puede leer como número de versión, se cae a "actualizar",
  // que es lo que pasa el 99% de las veces y el texto menos arriesgado.
  if not StrToVersion(SinV(Anterior), Vieja)
     or not StrToVersion(SinV('{#MyAppVersion}'), Nueva) then
  begin
    Result := casoActualizar;
    exit;
  end;
  if ComparePackedVersion(Nueva, Vieja) < 0 then
    Result := casoVolverAtras
  else
    Result := casoActualizar;
end;

procedure InitializeWizard();
var
  Anterior: String;
  Caso: Integer;
begin
  Anterior := VersionInstalada();
  Caso := QueSeEstaHaciendo(Anterior);
  CasoDeEstaCorrida := Caso;

  // OJO: el arreglo de argumentos NO puede quedar al principio de una línea.
  // Inno lee una línea que empieza con "[" como etiqueta de sección y aborta
  // con "Invalid section tag", aunque esté dentro de [Code].
  case Caso of
    casoActualizar:
      begin
        WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismUpdateTitle');
        WizardForm.WelcomeLabel2.Caption := FmtMessage(
          CustomMessage('PrismUpdateBody'), [SinV(Anterior), SinV('{#MyAppVersion}')]);
      end;
    casoReinstalar:
      begin
        WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismRepairTitle');
        WizardForm.WelcomeLabel2.Caption := FmtMessage(
          CustomMessage('PrismRepairBody'), [SinV(Anterior)]);
      end;
    casoVolverAtras:
      begin
        WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismDowngradeTitle');
        WizardForm.WelcomeLabel2.Caption := FmtMessage(
          CustomMessage('PrismDowngradeBody'), [SinV(Anterior), SinV('{#MyAppVersion}')]);
      end;
  else
    // El begin/end no es decorativo: el "else" de un case en Pascal Script
    // toma UNA sola sentencia, y sin envolverlo la compilación aborta con
    // "'END' expected" en la segunda línea.
    begin
      WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismFreshTitle');
      WizardForm.WelcomeLabel2.Caption :=
        FmtMessage(CustomMessage('PrismFreshBody'), [SinV('{#MyAppVersion}')]);
    end;
  end;
  // Va en los dos casos: actualizar tambien puede quedar bloqueado.
  WizardForm.WelcomeLabel2.Caption :=
    WizardForm.WelcomeLabel2.Caption + CustomMessage('PrismUnsignedNote');
end;

// El aviso de Smart App Control se muestra sobre la bienvenida, no antes de
// que aparezca el asistente: un cartel suelto sin ventana detras parece un
// error del propio instalador.
//
// AvisoSacMostrado: CurPageChanged vuelve a dispararse si el usuario va para
// atras, y repetir el mismo cartel es molesto.
procedure CurPageChanged(CurPageID: Integer);
var
  SinBotonesPropios: TArrayOfString;
begin
  // El botón de "Listo para instalar" dice siempre "Instalar", aunque se esté
  // actualizando o reinstalando. Que diga lo que va a pasar de verdad.
  if CurPageID = wpReady then
  begin
    case CasoDeEstaCorrida of
      casoActualizar: WizardForm.NextButton.Caption := CustomMessage('PrismBtnUpdate');
      casoReinstalar: WizardForm.NextButton.Caption := CustomMessage('PrismBtnRepair');
      casoVolverAtras: WizardForm.NextButton.Caption := CustomMessage('PrismBtnDowngrade');
    else
      WizardForm.NextButton.Caption := CustomMessage('PrismBtnFresh');
    end;
  end;

  if (CurPageID = wpWelcome) and (not AvisoSacMostrado)
     and SmartAppControlBloqueando() then
  begin
    AvisoSacMostrado := True;
    // TaskDialogMsgBox y no MsgBox: este texto es largo y necesita un titulo
    // propio arriba. MsgBox no acepta titulo —usa el del instalador— y todo
    // quedaba como un parrafo suelto.
    TaskDialogMsgBox(CustomMessage('PrismSacTitle'), CustomMessage('PrismSacBody'),
                     mbInformation, MB_OK, SinBotonesPropios, 0);
  end;
end;

