; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PrismHub"
; Tiene que coincidir con Compartir.esquema (lib/utils/compartir.dart)
; y con el intent-filter de AndroidManifest.xml.
#define MyAppScheme "prismhub"
#define MyAppPublisher "PrismHub"
#define MyAppURL "https://github.com/Litdemonick/Prism_Hub"
#define MyAppExeName "PrismHub.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3C6BC9E1-F61D-4FD6-BDA6-3BC203E88418}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=PrismHub-setup-{#MyAppVersion}
SetupIconFile=.\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Sin esto, ni instalar (sobre una versión ya corriendo) ni desinstalar
; cierran el proceso — Windows no mata un .exe corriendo solo porque se
; borró el archivo del disco, así que quedaba corriendo "fantasma" después
; de desinstalar. CloseApplications usa Restart Manager para detectarlo y
; cerrarlo (force = sin preguntar); RestartApplications=no porque no tiene
; sentido reabrir el reproductor solo.
CloseApplications=force
RestartApplications=no
; Idioma automático según Windows, sin preguntar. Inno 6 detecta solo por el
; idioma de la interfaz del sistema (la directiva LanguageDetection de Inno 5
; ya no existe: usarla aborta la compilación). Ver [Languages].
ShowLanguageDialog=no
; Y NO reutilizar el idioma de la instalacion anterior, que es lo que hace Inno
; por defecto (UsePreviousLanguage=yes). Al actualizar, Setup lee el valor
; "Inno Setup: Language" que dejo la instalacion previa y lo usa tal cual, sin
; llegar a detectar nada. Como las versiones hasta la 1.0.13 se publicaron con
; el instalador solo en ingles, ese valor quedo grabado como "english" en todas
; las maquinas: por mas que ahora se declare el espanol, la deteccion no
; alcanzaba a correr y el instalador seguia saliendo en ingles. Confirmado
; leyendo esa clave en una instalacion real.
UsePreviousLanguage=no
; La pantalla de bienvenida viene DESACTIVADA por defecto en Inno 6, y es
; justamente donde se avisa si esto es una actualización y entre qué versiones
; (ver InitializeWizard). Sin ella, el instalador arrancaba directo en "elegí
; carpeta" y nunca decía qué se estaba instalando ni sobre qué.
DisableWelcomePage=no
; Muestra "PrismHub <versión>" en el título del asistente.
AppVerName={#MyAppName} {#MyAppVersion}

[Languages]
; El instalador salía siempre en inglés, aunque Windows estuviera en español.
; Inno elige solo según el idioma de Windows y no pregunta nada
; (ShowLanguageDialog=no); si el sistema está en cualquier otro idioma cae en el
; primero de la lista, que es inglés.
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[CustomMessages]
; %1 = versión instalada, %2 = versión que se va a instalar.
english.PrismUpdateTitle=Updating PrismHub
spanish.PrismUpdateTitle=Actualizando PrismHub
english.PrismUpdateBody=PrismHub %1 is already installed. It will be updated to version %2.%n%nYour history, favorites and settings are kept: they are stored outside the program folder.
spanish.PrismUpdateBody=Ya tenés instalado PrismHub %1. Se va a actualizar a la versión %2.%n%nTu historial, favoritos y ajustes se conservan: se guardan fuera de la carpeta del programa.
english.PrismFreshTitle=Installing PrismHub
spanish.PrismFreshTitle=Instalando PrismHub
english.PrismFreshBody=PrismHub %1 will be installed on this computer.%n%nAnime, manga and series through extensions that install and update on their own.
spanish.PrismFreshBody=Se va a instalar PrismHub %1 en este equipo.%n%nAnime, manga y series mediante extensiones que se instalan y actualizan por su cuenta.
; Al desinstalar. Se PREGUNTA en vez de borrar directo: mucha gente desinstala
; para reinstalar, y llevarse el historial sin avisar no se puede deshacer.
english.PrismWipeTitle=Remove your data as well?
spanish.PrismWipeTitle=¿Borrar también tus datos?
english.PrismWipeBody=Do you also want to delete your history, favourites, settings and installed extensions?%n%nThey live outside the program folder, so by default they are KEPT — that way reinstalling picks up where you left off.%n%nChoose Yes only if you want to leave nothing behind. This cannot be undone.
spanish.PrismWipeBody=¿Querés borrar también tu historial, favoritos, ajustes y extensiones instaladas?%n%nEstán fuera de la carpeta del programa, así que por defecto se CONSERVAN — así, si reinstalás, seguís donde estabas.%n%nElegí Sí solo si no querés que quede ningún rastro. Esto no se puede deshacer.
english.PrismWipeDone=Your data was deleted.
spanish.PrismWipeDone=Se borraron tus datos.
english.PrismFirewall=Allowing PrismHub through the firewall (needed to cast to a TV)...
spanish.PrismFirewall=Permitiendo PrismHub en el firewall (hace falta para transmitir a un televisor)...
english.PrismWipeKept=Your data was kept at:%n%1
spanish.PrismWipeKept=Tus datos se conservaron en:%n%1

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Enlaces compartidos: prismhub://detail?package=...&url=...
;
; Windows resuelve un esquema propio mirando HKCR\<esquema>. Sin estas claves,
; el enlace que alguien recibe por chat es texto muerto: no hay nada que le
; diga al sistema que PrismHub lo entiende.
;
; Van bajo Software\Classes del usuario y no en HKEY_CLASSES_ROOT a secas: el
; instalador puede correr sin permisos de administrador, y ahi HKCR no se puede
; escribir. Registrado por usuario funciona igual para quien instalo.
;
; "URL Protocol" tiene que existir aunque este vacio — es la marca por la que
; Windows reconoce la clave como un esquema y no como un tipo de archivo.
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}"; ValueType: string; ValueName: ""; ValueData: "URL:{#MyAppName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
; El "%1" es la direccion completa que se abrio, y va entre comillas porque
; puede traer espacios y ampersands: sin ellas el enlace llega cortado en el
; primer simbolo raro.
Root: HKA; Subkey: "Software\Classes\{#MyAppScheme}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Permiso de FIREWALL para transmitir a un televisor.
;
; Al castear, el video no lo baja el televisor de internet: lo sirve ESTE
; equipo, que abre un servidor en la red local y le pasa la direccion. Windows
; bloquea por defecto las conexiones entrantes de un programa sin regla, asi
; que el televisor pedia el video y no le contestaba nadie — se quedaba en
; negro con la barra en 00:00 y desde afuera parecia que el televisor no
; soportaba el formato. Comprobado en un equipo real: cero reglas para el app y
; politica de entrada en bloquear.
;
; Solo en redes privadas (domesticas): en una red publica no hay nada que
; transmitir y no corresponde abrir nada.
;
; skipifdoesntexist: si el instalador corre sin permisos de administrador la
; regla no se va a poder crear, y eso no es motivo para que falle la
; instalacion — el casteo es una funcion mas, no el app entero.
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"""; Flags: runhidden waituntilterminated skipifdoesntexist; StatusMsg: "{cm:PrismFirewall}"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes profile=private"; Flags: runhidden waituntilterminated skipifdoesntexist; StatusMsg: "{cm:PrismFirewall}"
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Se quita al desinstalar: una regla apuntando a un programa que ya no existe
; no hace daño, pero tampoco tiene por que quedar.
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"""; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "QuitarReglaFirewall"

[Code]
// La versión llega desde el workflow como nombre del tag ("v1.0.13"), y lo
// mismo quedó guardado en el registro. Mostrarla tal cual daba "versión
// v1.0.13"; se le saca la v para que el texto se lea normal.
function SinV(const S: String): String;
begin
  Result := S;
  if (Length(Result) > 1) and ((Result[1] = 'v') or (Result[1] = 'V')) then
    Result := Copy(Result, 2, Length(Result) - 1);
end;

// Versión que ya está instalada, leída de la clave de desinstalación que crea
// el propio Inno. Cadena vacía si es una instalación nueva.
//
// OJO: el GUID va literal y tiene que coincidir con AppId de [Setup]. No se usa
// SetupSetting("AppId") porque ahí el valor viene con la llave doble de escape
// ({{...}) y quedaría una llave de más en la ruta del registro.
//
// Se miran las dos vistas del registro y las dos raíces: el instalador corre en
// 32 bits, así que HKLM le resuelve a Wow6432Node, pero una instalación hecha
// por otro medio pudo dejar la clave en la vista de 64 bits o por usuario.
function VersionInstalada(): String;
var
  Clave: String;
  Valor: String;
begin
  Result := '';
  Clave := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{3C6BC9E1-F61D-4FD6-BDA6-3BC203E88418}_is1';
  if RegQueryStringValue(HKLM, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKCU, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKLM64, Clave, 'DisplayVersion', Valor) then
    Result := Valor
  else if RegQueryStringValue(HKCU64, Clave, 'DisplayVersion', Valor) then
    Result := Valor;
end;

// Dónde deja el app sus cosas, fuera de la carpeta del programa.
//
// {userdocs} y NO una ruta armada a mano: la carpeta Documentos puede estar
// redirigida a OneDrive y además traducida —comprobado en un equipo real, ahí
// vive en OneDrive\Documentos\PrismHub—. Esa constante la resuelve Windows, así
// que sigue la redirección; una ruta fija habría borrado la carpeta equivocada,
// o peor, ninguna, dejando creer que se limpió.
function CarpetaDatos(): String;
begin
  Result := ExpandConstant('{userdocs}\PrismHub');
end;

function CarpetaCache(): String;
begin
  Result := ExpandConstant('{localappdata}\Temp\PrismHub');
end;

function CarpetaSoporte(): String;
begin
  Result := ExpandConstant('{userappdata}\com.prismhub');
end;

// Al desinstalar: se pregunta y, si el usuario quiere, se borra todo.
//
// usPostUninstall y no usUninstall: recién ahí ya se quitaron los archivos del
// programa, así que si algo falla al borrar los datos el desinstalado igual
// quedó hecho.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Datos: String;
  Borrados: Boolean;
begin
  if CurUninstallStep <> usPostUninstall then
    exit;

  Datos := CarpetaDatos();
  // Sin datos guardados no se pregunta nada: sería una ventana de más para
  // decidir sobre algo que no existe.
  if not DirExists(Datos) and not DirExists(CarpetaCache())
     and not DirExists(CarpetaSoporte()) then
    exit;

  if MsgBox(CustomMessage('PrismWipeBody'), mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
  begin
    Borrados := True;
    if DirExists(Datos) then
      if not DelTree(Datos, True, True, True) then Borrados := False;
    if DirExists(CarpetaCache()) then
      if not DelTree(CarpetaCache(), True, True, True) then Borrados := False;
    if DirExists(CarpetaSoporte()) then
      if not DelTree(CarpetaSoporte(), True, True, True) then Borrados := False;
    // Se avisa igual aunque algo no se haya podido borrar: quedarse callado
    // dejaría creer que no quedó nada cuando sí quedó.
    if Borrados then
      MsgBox(CustomMessage('PrismWipeDone'), mbInformation, MB_OK)
    else
      MsgBox(FmtMessage(CustomMessage('PrismWipeKept'), [Datos]), mbInformation, MB_OK);
  end
  else
    // Se dice DÓNDE quedaron: si no, el usuario no tiene forma de encontrarlos
    // para borrarlos a mano más adelante.
    MsgBox(FmtMessage(CustomMessage('PrismWipeKept'), [Datos]), mbInformation, MB_OK);
end;

procedure InitializeWizard();
var
  Anterior: String;
begin
  Anterior := VersionInstalada();
  if Anterior <> '' then
  begin
    WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismUpdateTitle');
    // OJO: el arreglo de argumentos NO puede quedar al principio de una línea.
    // Inno lee una línea que empieza con "[" como etiqueta de sección y aborta
    // con "Invalid section tag", aunque esté dentro de [Code].
    WizardForm.WelcomeLabel2.Caption := FmtMessage(
      CustomMessage('PrismUpdateBody'), [SinV(Anterior), SinV('{#MyAppVersion}')]);
  end
  else
  begin
    WizardForm.WelcomeLabel1.Caption := CustomMessage('PrismFreshTitle');
    WizardForm.WelcomeLabel2.Caption :=
      FmtMessage(CustomMessage('PrismFreshBody'), [SinV('{#MyAppVersion}')]);
  end;
end;

