name: Feature Request
description: Propón una nueva funcionalidad
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: ¿Qué problema resuelve esta feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas (opcional)
